### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by galen1423** [fthx/snap-manager-lite#1]
Hello,

Thanks for this very useful extension to me. Consider you to port Snap Manager to Gnome Shell 45 in a near future?

Thank you again for your work.

Regards

**Comment by fthx** [comment]
Hi,

This should not be a huge step forward.
But if there are some blocking changes I won't update it. (I updated many ext to v45, so the syntax is not a problem)

**Comment by fthx** [comment]
Maybe tomorrow.

**Comment by fthx** [comment]
https://extensions.gnome.org/review/45571
