### ISSUE TITLE
Snap Icon Missing

### ISSUE THREAD

**Issue by galen1423** [fthx/snap-manager-lite#2]
Hello,

Snap software icon is not displaying in top bar but write in full `Snaps` 

![Capture d’écran du 2023-09-28 11-45-36](https://github.com/fthx/snap-manager-lite/assets/24211031/66a2082c-c1f7-4e1e-83f1-dc98a35d06cd)

Regards

**Comment by fthx** [comment]
Yes, I had a looot of tiny problems when updating.
There's a bug in GS X11 session that make me believe it was extension's fault...
So atm you have a label, there are some changes importing icons too. So I know how to do that but I had to clean the code to find some more important issues I got.

You can have an icon if you do use Yaru icons (see two commented lines in extension.js).
