### ISSUE TITLE
Compatibility with Gnome 46

### ISSUE THREAD

**Issue by Alfagiovanni56** [fthx/snap-manager-lite#3]
I hope this very useful gnome extension is/will be compatible with Gnome 46  and if not, will be made compatible with Gnome 46 as soon as possible. It would be a real pity if the extension would not be available for users of the upcoming Ubuntu 24.4 LTS, which will be released this week and ships with Gnome 46. I use it really every day, for various purposes (check of available updates, check of recent changes and sometime to change the channel of a snap or to revert to earlier versions. Especially in these latter cases the extension offers an important efficiency gain for not too experienced users, as compared to using the right commands in a terminal themselves.

**Comment by fthx** [comment]
Simply adding 46 in metadata works?

**Comment by isparnid** [comment]
Hello,
Insert "46" in metadata.json but  it didn't work. This is message in the logs :

Extension snap-manager-lite@fthx: SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/misc/extensionUtils.js:4:0

Stack trace:
  @file:///home/daniel/.local/share/gnome-shell/extensions/snap-manager-lite@fthx/extension.js:11:24
  @resource:///org/gnome/shell/ui/init.js:21:20

Any idea please ?

**Comment by fthx** [comment]
It works using GS 46 if you change "add_actor" to "add_child" (1 occurrence in St.Label part).
If I update this extension, I'll update snap commands too, there are some new stuff.

**Comment by isparnid** [comment]
thank you, it works!
